### ISSUE TITLE
Analysis fails due to data that is not unpacked

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-alpha#212]
Hey guys,

I tried `make analysis` and it fails at a certain point because at least one bold.nii.gz doesn't get unpacked by `make data`.

If any of you are not getting killed by finals I'd appreciate if you could take a look. If you're all super busy that's fine, I'll work it out on my own. Let me know if you'll have a chance to look at it today

**Comment by rossbar** [comment]
Actually, it appears to be a path error, not an unpacking error

**Comment by janewliang** [comment]
#213 hopefully fixes this. Let me know!

**Comment by rossbar** [comment]
The changes helped, but ran into another issue (I'm working remotely so I can't copy and paste the error message, here's a screen grab):

![alpha_error](https://cloud.githubusercontent.com/assets/1268991/11833863/d2caa3ae-a37b-11e5-8797-8eede1b90187.png)

**Comment by benjaminleroy** [comment]
Dang. I just fixed it and did a completely new download of the data to run everything

**Comment by hiroto-udagawa** [comment]
@rossbar 
I want to apologize. I ran the code to prepare our paper images and figures 10x over so I was really surprised by this error. It turns out that Mac and Linux are different in that Mac files are not case-sensitive and Linux files are: http://www.informit.com/articles/article.aspx?p=1144082&seqNum=4

I'm really sorry if you have any other errors of this sort. I was completely unaware of this difference. Considering you are on the second to last script you need to run, I hope you don't run into this issue again.

**Comment by benjaminleroy** [comment]
Thank you for being so kind about it by the way

**Comment by rossbar** [comment]
No problem, these type of issues occur all the time. In hindsight, we should have had each group pair up with another group and attempt to run each other's projects on their own machines in order to catch issues like this in a "dry run"; unfortunately everyone was so busy (including us) that this plan got lost in the wash. These are the types of things that tools like TravisCI are supposed to help with, but as you've now experienced first hand, tools like that don't provide bulletproof solutions. 

If you guys have time, it would make things a lot easier on me if you could finalize the last couple file-name changes or provide updated instructions for running the last set of analysis. This would definitely be less of a priority than preparation for any remaining finals and the like, so it's not necessary, but it would be very convenient for `make analysis` to go to completion. If you don't have time, just affix the **wontfix** label to this issue and I will know to figure it out manually

**Comment by janewliang** [comment]
Yeah. The filename for adjusted R^2 should actually be "AdjR2_2.txt". Confirmed that this runs on Linux. I don't have the kind of internet speed to re-download the data in a feasible amount of time, but I tried to clear out the files that I know were user-generated before running the code and final scripts one-by-one on my computer. If anybody cares, we're still raising a "mean of empty slice" warning message in code/utils/scripts/model_selection.py. But otherwise, I'm not getting other errors, which of course doesn't actually guarantee that no errors exist. 

Thanks for taking them the time to tell us and give us all the error messages. In terms of providing updated instructions for running the last set of analysis, do you mean you'd like us to document all of the little things we needed to fix to get it to run? Otherwise, (in theory) `make analysis` should work now without additional instructions.

**Comment by rossbar** [comment]
No you don't have to document all of the changes you made to get it to run (git does this for you!) I was just asking if there were make commands to only run individual portions of the analysis. `make analysis` takes a significant amount of time and the entire analysis reruns every time instead of a subset of them. I will run everything again though, thanks for the quick responses!

**Comment by janewliang** [comment]
`make analysis` at the top-level directory is broken into two steps, so if desired, you can go to the `final` directory and then run `make data` before running `make images` and that should do the same thing as running `make analysis` in the top directory. Based on your previous error message, you've made it through `make data`, which is the more computationally-intensive part. You'd still have to get through several script files when running `make images` (which is where your last error was), but that should save some time. We can add this to the top README (the `final` README explains the two separate commands already).

**Comment by rossbar** [comment]
Alright everything has worked and I was able to complete the analysis and generate your final report. Thanks for taking the time to look into this stuff, esp. during finals week!
